services:
  db:
    image: postgres:15
    container_name: my_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opmet_db

  backend:
    build: ./backend
    container_name: my_backend_api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/opmet_db

  frontend:
    build: ./frontend
    container_name: my_frontend_app
    ports:
      - "8501:8501"
    depends_on:
      - backend